spring:
  hadoop:
    fsUri: hdfs://ecsc00a022c6.epam.com:8020
    resourceManagerHost: ecsc00a022c6.epam.com
  yarn:
    appName: gs-yarn-basic
    applicationDir: /app/gs-yarn-basic/
    client:
      files:
        - "file:gs-yarn-basic-dist/target/gs-yarn-basic-dist/gs-yarn-basic-container-0.1.0.jar"
        - "file:gs-yarn-basic-dist/target/gs-yarn-basic-dist/gs-yarn-basic-appmaster-0.1.0.jar"
      launchcontext:
        archiveFile: gs-yarn-basic-appmaster-0.1.0.jar
        arguments:
          --my.appmaster.filePath: ${my.client.filePath:notset1}
    appmaster:
      containerCount: 1
      launchcontext:
        archiveFile: gs-yarn-basic-container-0.1.0.jar
        arguments:
          --my.container.filePath: ${my.appmaster.filePath:notset2}